# Generated by Django 5.1.5 on 2025-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0002_delete_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('tracking_param', models.CharField(choices=[('reps', 'repetitions'), ('duration', 'duration')], max_length=15)),
            ],
        ),
    ]
