# Generated by Django 5.1.5 on 2025-01-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='tracking_param',
            field=models.CharField(choices=[('duration', 'Duration')]),
        ),
    ]
