# Generated by Django 5.1.5 on 2025-01-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercises_tracking_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='tracking_param',
        ),
    ]
