# Generated by Django 5.1.5 on 2025-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercises_tracking_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='tracking_param',
            field=models.CharField(choices=[('duration', 'Duration')], default='reps'),
        ),
    ]
