# Generated by Django 5.1.5 on 2025-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercises_tracking_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='tracking_param',
            field=models.CharField(choices=[('reps', 'Reps'), ('duration', 'Duration')], default='reps'),
        ),
    ]
