# Generated by Django 5.1.5 on 2025-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_exercises_tracking_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='tracking_param',
            field=models.CharField(choices=[('reps', 'repetitions'), ('duration', 'duration')], default='reps'),
        ),
    ]
