# Generated by Django 5.1.5 on 2025-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_exercises_tracking_param'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('tracking_param', models.CharField(choices=[('reps', 'Repetitions'), ('duration', 'Duration')], default='reps')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
