# Generated by Django 5.1.5 on 2025-01-26 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_exercises_delete_publicexercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercises',
            constraint=models.UniqueConstraint(fields=('user', 'value'), name='unique_exercise'),
        ),
    ]
