# Generated by Django 5.1.5 on 2025-01-26 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_exercises_unique_exercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercises',
            name='unique_exercise',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='exercises',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', False)), fields=('user', 'value'), name='unique_user_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercises',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'value'), name='unique_exercise'),
        ),
    ]
