# Generated by Django 5.1.5 on 2025-01-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_remove_exercises_unique_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercises',
            name='unique_user_exercise',
        ),
        migrations.RemoveConstraint(
            model_name='exercises',
            name='unique_exercise',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='is_default',
        ),
    ]
