# Generated by Django 5.1.5 on 2025-01-26 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_remove_exercises_unique_user_exercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercises',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('value', 'user'), name='unique_user_generated_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercises',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('value',), name='unique_default_exercise'),
        ),
    ]
