# Generated by Django 5.1.5 on 2025-01-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_rename_workouts_workout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocks',
            new_name='Block',
        ),
    ]
