# Generated by Django 5.1.5 on 2025-01-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_blockexercise_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockexercisedata',
            name='field',
            field=models.CharField(choices=[('reps', 'Repetitions'), ('duration', 'Duration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blockexercisedata',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
