# Generated by Django 5.1.5 on 2025-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0022_alter_blockexercisedata_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockexercisedata',
            name='field',
            field=models.CharField(choices=[('sets', 'Sets'), ('reps', 'Repetitions'), ('duration', 'Duration')], max_length=20),
        ),
    ]
