# Generated by Django 5.1.5 on 2025-01-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_alter_workout_options_workout_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created_at']},
        ),
    ]
