# Generated by Django 5.1.5 on 2025-01-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0027_alter_exercise_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_completed',
            field=models.BooleanField(null=True),
        ),
    ]
