# Generated by Django 5.1.5 on 2025-01-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0028_remove_activity_date_completed_activity_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
