# Generated by Django 5.1.5 on 2025-01-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_rename_is_completed_activity_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
